### ISSUE TITLE
Mat-Stepper showing all steps when used in Tabs

### ISSUE THREAD

**Issue by Stexxen** [angular/components#10965]
#### Bug, feature request, or proposal:
Bug in mat-vertical-stepper

#### What is the expected behavior?
On the 1st Tab, the bodies of the 2nd and subsequent Steps should not be visible
On the 2nd tab, the Bodies of the 2nd and subsequent steps should not be visible.
 

#### What is the current behavior?
On the 1st Tab, the bodies of the 2nd and subsequent Steps are not visible as expected
![image](https://user-images.githubusercontent.com/4494301/39151232-4261473e-470a-11e8-9790-11f8100f05f9.png)

On the 2nd tab, the 2nd and subsequent steps are visible
![image](https://user-images.githubusercontent.com/4494301/39151279-5d936096-470a-11e8-9f0a-f688b2922e99.png)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-tcbhuy

Click Tab2 or Tab3

The steps are only hidden on the 1st tab (Tab1).

**Comment by Stexxen** [comment]
On the 1st Tab, a hidden step has the following HTML
![image](https://user-images.githubusercontent.com/4494301/39151701-aca1e71a-470b-11e8-83b4-ef6e5c5a6c7b.png)
On the 2nd Tab, the same step has the following HTML
![image](https://user-images.githubusercontent.com/4494301/39151756-c54ad92a-470b-11e8-80b1-d991d9a5fdb1.png)

Note the extra `style="height: 0px; visibility: hidden;"`

**Comment by primissus** [comment]
Did you find any solution or any workaround?

**Comment by divyav17** [comment]
https://stackblitz.com/edit/angular-mat-stepper-in-mat-tab-group?file=app%2Fstepper.component.ts

Workaround using ngIf

**Comment by vip20** [comment]
I am trying to use mat-stepper and need this actually as a feature. Open all steps and close all steps.

**Comment by bijanmmarkes** [comment]
This is also a functionality I need, to have them all expanded at one, simply to use the design on the left. while having custom 

> I am trying to use mat-stepper and need this actually as a feature. Open all steps and close all steps.

I also need mat-stepper to have all steps expanded at once as a feature.

**Comment by mantsch** [comment]
Heres a quick and dirty css fix. Prevents opening all stepper contents when switching between tabs.

`::ng-deep [ng-reflect-selected="false"] + .mat-vertical-content-container > .mat-vertical-stepper-content {
  display: none !important;
}
`

**Comment by vilbara** [comment]
@mantsch this won't work with PROD-build as ng-reflect-* properties are not available.

**Comment by mmalerba** [comment]
This has been fixed, as demonstrated in this updated stackblitz https://stackblitz.com/edit/angular-tcbhuy-xx2aco?file=main.ts

**Comment by SK-Commit** [comment]
I still get the bug, after deleting node_modules, package-lock.json, and updating package.json to newest angular versions of all packages in a fresh project.

Note: The project is generated through the generator: "NGX-Rocket", but doesn't seem to be where the error comes from.

Can be seen and tested here:
https://github.com/SK-Commit/angular-stepper-tabs-bug

Clone project -> npm install -> npm start -> go to localhost:4200
