### ISSUE TITLE
Form-Field label gap not calculated in Mat-Tab-Group in 6.4.6

### ISSUE THREAD

**Issue by OlufemiOyewole** [angular/components#12780]
#### Bug:
form-field-outline conditionally strikes through its label when in a mat-tab.
<img width="235" alt="screen shot 2018-08-21 at 2 59 06 pm" src="https://user-images.githubusercontent.com/17495353/44423015-e0125800-a552-11e8-9c5b-87ae56755575.png">
<img width="239" alt="screen shot 2018-08-21 at 2 59 16 pm" src="https://user-images.githubusercontent.com/17495353/44423014-df79c180-a552-11e8-8e8f-eac020d46a9a.png">
<img width="249" alt="screen shot 2018-08-21 at 2 59 28 pm" src="https://user-images.githubusercontent.com/17495353/44423013-df79c180-a552-11e8-888b-a28dd09137e3.png">

#### What is the expected behavior?
The form-field-outline should not strike through the label.

#### What is the current behavior?
form-field-outlines in all mat-tabs of a mat-tab-group, strike through their labels. Except in the tab that is initially displayed.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-je8fzq

#### What is the use-case or motivation for changing an existing behavior?
(not applicable)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.3
Angular Material 6.4.6
Chrome 68, Safari 11.1.2

#### Is there anything else we should know?
This seems related to #12765, #12555 and #12767

**Comment by OlufemiOyewole** [comment]
I noticed that this bug has been fixed in version 6.4.7 and above.
Should it be closed?

**Comment by MlleBeuze** [comment]
Hi,

Thank you @OlufemiOyewole , I was wondering why I was having this bug, I understand now that it's with Material tabs. I'm using the version "^6.4.7" of Material, and the bug is still there.

Will this bug be fixed?

Thank you.

**Comment by OlufemiOyewole** [comment]
Hi @MlleBeuze 

It works fine here for version 6.4.7: https://stackblitz.com/edit/angular-gef43c
It does not work for version 6.4.6: https://stackblitz.com/edit/angular-je8fzq

The only difference between the two is the Angular Material version. Check it out.

**Comment by MlleBeuze** [comment]
Hi there :),

Well I still have the bug, only on mat-tab :/

<img width="565" alt="Screenshot 2019-04-05 at 17 38 52" src="https://user-images.githubusercontent.com/13280573/55639497-d0860d80-57c9-11e9-8c77-f3985e795cc0.png">
<img width="581" alt="Screenshot 2019-04-05 at 17 38 58" src="https://user-images.githubusercontent.com/13280573/55639498-d0860d80-57c9-11e9-82d5-e012a36f10b3.png">
<img width="564" alt="Screenshot 2019-04-05 at 17 39 05" src="https://user-images.githubusercontent.com/13280573/55639499-d11ea400-57c9-11e9-93e0-2c7f2ddf78b1.png">

And my version is "@angular/material": "^6.4.7".

**Comment by OlufemiOyewole** [comment]
@MlleBeuze 
Could you reproduce the issue in https://stackblitz.com to make it accessible?

**Comment by MlleBeuze** [comment]
I'm sorry, I've just realised I'm using another way of doing the tabs, which is not mat-tab, my bad!

Have a good WE 👍

**Comment by crisbeto** [comment]
Looks like the related fix was merged a long time ago, but the PR wasn't tagged properly so the issue wasn't closed.
