### ISSUE TITLE
The MatButtonToggle component throws several errors in ng test.

### ISSUE THREAD

**Issue by ramyasingamsetti** [angular/components#16630]
@crisbeto 
The MatButtonToggle component throws several errors in ng test with Ivy compiler enabled.

Reproduction
Not able to reproduct with Stackblitz

Expected Behavior
ng test should not throw any errors

Actual Behavior
ng test throws the following errors:

{
  stacktrace: TypeError: Cannot read property 'isSelected' of undefined at MatButtonToggleGroup.push../node_modules/@angular/material/esm5/button-toggle.es5.js.MatButtonToggleGroup._isSelected (http://localhost:9876/node_modules/@angular/material/esm5/button-toggle.es5.js?:368:1) at MatButtonToggle.push../node_modules/@angular/material/esm5/button-toggle.es5.js.MatButtonToggle.ngOnDestroy (http://localhost:9876/node_modules/@angular/material/esm5/button-toggle.es5.js?:645:1) at callProviderLifecycles (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:22422:1) at callElementProvidersLifecycles (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:22390:1) at callLifecycleHooksChildrenFirst (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:22380:1) at destroyView (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:23442:1) at callViewAction (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:23568:1) at execComponentViewsAction (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:23490:1) at destroyView (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:23441:1) at callWithDebugContext (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:24177:1)
ngDebugContext: DebugContext_ {view: {…}, nodeIndex: 35, nodeDef: {…}, elDef: {…}, elView: {…}}
ngErrorLogger: ƒ ()
message: "Cannot read property 'isSelected' of undefined"
stack: "TypeError: Cannot read property 'isSelected' of undefined↵    at MatButtonToggleGroup.push../node_modules/@angular/material/esm5/button-toggle.es5.js.MatButtonToggleGroup._isSelected (http://localhost:9876/node_modules/@angular/material/esm5/button-toggle.es5.js?:368:1)↵    at MatButtonToggle.push../node_modules/@angular/material/esm5/button-toggle.es5.js.MatButtonToggle.ngOnDestroy (http://localhost:9876/node_modules/@angular/material/esm5/button-toggle.es5.js?:645:1)↵    at callProviderLifecycles (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:22422:1)↵    at callElementProvidersLifecycles (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:22390:1)↵    at callLifecycleHooksChildrenFirst (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:22380:1)↵    at destroyView (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:23442:1)↵    at callViewAction (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:23568:1)↵    at execComponentViewsAction (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:23490:1)↵    at destroyView (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:23441:1)↵    at callWithDebugContext (http://localhost:9876/node_modules/@angular/core/fesm5/core.js?:24177:1)"
__proto__: Error
constructor: ƒ TypeError()
message: ""
name: "TypeError"
toString: ƒ toString()
__proto__: Object
__proto__: Object
}

Angular CLI: 7.0.7
Node: 10.9.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router
Package Version
@angular-devkit/architect          0.10.7
@angular-devkit/build-angular      0.10.7
@angular-devkit/build-optimizer    0.10.7
@angular-devkit/build-webpack      0.10.7
@angular-devkit/core               7.0.7
@angular-devkit/schematics         7.0.7
@angular/cdk                       7.3.7
@angular/cli                       7.0.7
@angular/flex-layout               7.0.0-beta.24
@angular/material                  7.3.7
@angular/material-moment-adapter   7.3.7
@ngtools/webpack                   7.0.7
@schematics/angular                7.0.7
@schematics/update                 0.10.7
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.19.1

Below is my code.

          <mat-button-toggle-group #toggleid="matButtonToggleGroup" value="value1" 
                        (change)="change(toggleid.value)">

           <mat-button-toggle value="value1" checked="true">value1</mat-button-toggle>
            <mat-button-toggle value="value2">value2</mat-button-toggle>
            <mat-button-toggle value="value3">value3</mat-button-toggle>
       </mat-button-toggle-group>

![matbuttomtoggle](https://user-images.githubusercontent.com/53302206/62025704-9916f300-b1f6-11e9-888d-644a77488586.jpg)

**Comment by crisbeto** [comment]
It was fixed in https://github.com/angular/components/pull/16587 as few days ago.

**Comment by ramyasingamsetti** [comment]
> It was fixed in #16587 as few days ago.

Yes. I have seen the fix and made code changes as per changes but still facing issue in angular material version 7.3.7.i don't know the reason.
