### ISSUE TITLE
Not able to create nested mat-stepper's since 9.0.0

### ISSUE THREAD

**Issue by mhosman** [angular/components#18448]
If I try to create a nested mat-stepper, all the steps of the child stepper are assigned to the parent one. This is happening since 9.0.0 update.

**Comment by tinchoel10** [comment]
Same issue here! My app is broken since 9.0 update.

**Comment by mhosman** [comment]
Pleassse! Fix this issue!!

**Comment by nandhagk** [comment]
I am using @angular/material: 10.1.3
And I am also getting this issue
`<mat-horizontal-stepper #parentStepper>
  <mat-step>
    <ng-template matStepLabel>Parent 1</ng-template>
    <mat-horizontal-stepper #childStepper>
      <mat-step>
        <ng-template matStepLabel>Child 1</ng-template>
      </mat-step>
      <mat-step>
        <ng-template matStepLabel>Child 2</ng-template>
      </mat-step>
    </mat-horizontal-stepper>
  </mat-step>
  <mat-step>
    <ng-template matStepLabel>Parent 2</ng-template>
  </mat-step>
</mat-horizontal-stepper>`

Results in 

![](https://i.stack.imgur.com/icbTE.png)

**Comment by crisbeto** [comment]
The fix was merged a few days ago and hasn't been released yet. You can look at the changelog to see when things are being released. https://github.com/angular/components/blob/master/CHANGELOG.md

**Comment by nandhagk** [comment]
Thanks a lot

**Comment by mhosman** [comment]
@crisbeto This is still not working okay in 10.2.0-rc.0. If you define a template inside a nested mat-stepper, the template also will be applyed to the parent one. This is wrong, it should only apply the template to that specific stepper.
