### ISSUE TITLE
Button (mat-icon-button): Icon is not centered correctly

### ISSUE THREAD

**Issue by eminvegan** [angular/components#22832]
Components: https://material.angular.io/components/button/overview#button-overview

#### Actual Behavior / Expected Behavior

![bug-report_angular-material_button_mat-icon-button](https://user-images.githubusercontent.com/47469054/119910833-4c1e1800-bf58-11eb-9833-93d6227fbbbd.jpg)

#### Environment
- Angular: 12.0.1
- CDK/Material: 12.0.1
- Browser: Google Chrome (90.0.4430.212)
- Operating System: macOS Big Sur (11.4)

#### Temporary Fix

I don't know if the bug is because of the icon or because of the css. But I added following to styles.css

```scss
.mat-icon-button {
  display: flex !important;
  justify-content: center;
  justify-items: center;
  align-content: center;
  align-items: center;
  .mat-button-wrapper {
    display: block;
    width: 24px;
    height: 24px;
    margin: auto;
    mat-icon {
      vertical-align: top;
    }
  }
}
```

**Comment by crisbeto** [comment]
We made an attempt at fixing this a long time ago, but it ended up being difficult to land, because it broke a lot of screenshot tests. This should be fixed in the `MatButtonModule` inside `@angular/material-experimental/mdc-button`.

**Comment by leomayer** [comment]
Any progress on this issue? To my understanding this isn't fixed up till now. But would be great to be fixed! 

The very first perception  would suggest that there is something wrong - but hard to figure out what it is. Unless you are specialist ;-)

**Comment by amysorto** [comment]
Closing this bug since this is centered now in the new MDC based components coming soon in v15.
