### ISSUE TITLE
bug(MatTree): padding is not recomputed when moving a node inside/outside an expandable node

### ISSUE THREAD

**Issue by poirierlouis** [angular/components#29959]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

As `TreeControl` is deprecated, I started migrating to the latest API using `childrenAccessor`. So far so good, except for one case not working any more.

I'm using `matTreeNodePadding` and `matTreeNodePaddingIndent` on `<mat-tree-node>`. When I move a node inside/outside of an expandable node, padding is not recomputed as-is.

Expanding/collapsing the parent node in which the node was moved, will recompute its padding though.

### Reproduction

I'm working on an open-source project, so I don't have a small example to share for now.

Steps to reproduce:
1. Clone branch `https://github.com/poirierlouis/FellowImGui/tree/refactor/mat-tree`
2. `npm install`
3. `npm run start`
4. Open browser in `localhost:4200/editor`
5. Replicate actions like in video below:

![https://github.com/user-attachments/assets/8a0b04bd-d488-4164-90bc-4acac70324af](https://github.com/user-attachments/assets/8a0b04bd-d488-4164-90bc-4acac70324af)

You can find code related to `<mat-tree>` in:
- fig-tree: [component](https://github.com/poirierlouis/FellowImGui/blob/refactor/mat-tree/src/app/pages/editor/tree/tree.component.ts) + [template](https://github.com/poirierlouis/FellowImGui/blob/refactor/mat-tree/src/app/pages/editor/tree/tree.component.html)

`dataSource` is set with a [plain array](https://github.com/poirierlouis/FellowImGui/blob/056ef433f1001dd4df6a288d577a3ef8ac47b6d8/src/app/pages/editor/tree/tree.component.ts#L84).
When changed, `dataSource` is set with a [new array](https://github.com/poirierlouis/FellowImGui/blob/056ef433f1001dd4df6a288d577a3ef8ac47b6d8/src/app/pages/editor/tree/tree.component.ts#L99). That is, only the root of `dataSource` is changed with a new array reference. It doesn't cascade down through children.

Maybe it is related? Should the entire tree be cloned somehow, to trigger changes detection?

### Expected Behavior

When a node is moved inside/outside of an expandable node (level is changed), padding should be recomputed based on the new level of the node.

### Actual Behavior

Padding of the node is not updated when moving the node inside/outside of an expandable node.

### Environment

- Angular: 18.2.10
- CDK/Material: 18.2.11
- Browser(s): Firefox / Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by wagnermaciel** [comment]
Hi @poirierlouis, would you be able to provide a stackblitz example of this issue? It is difficult to debug this only from the code & video you shared.

**Comment by poirierlouis** [comment]
Hi @wagnermaciel thanks for the quick answer. Yes I'll try and write an example to reproduce this issue.

**Comment by poirierlouis** [comment]
@wagnermaciel , I could definitely reproduce this issue, see [Stackblitz](https://stackblitz.com/~/github.com/poirierlouis/ng-issue-29959) example.

**Comment by wagnermaciel** [comment]
@BobobUnicorn Is this resolved by https://github.com/angular/components/pull/29751?

**Comment by poirierlouis** [comment]
fyi, this issue is still present when trying with Angular v19.1.6 (latest as of today).

**Comment by Leonardonline** [comment]
Just wondering if there have been any news after 8 months.
