### ISSUE TITLE
bug(DragDrop): dragHandle not working in an table context

### ISSUE THREAD

**Issue by rbalet** [angular/components#30576]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

using `cdkDragHandle` inside a `mat-table` context does not work

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-starter-wgm2bvcc?file=src%2Fmain.ts
Steps to reproduce:
1. `cdkDragHandle` is on the mat-icon, but works on the entire line

### Expected Behavior

Only the `cdkDragHandle` should be draggable

### Actual Behavior

The entire row is draggable

### Environment

- Angular: 19.1.7
- CDK/Material: 19.1.5
- Browser(s): Chrominium 133.0.6943.127
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
This was fixed some time ago by https://github.com/angular/components/pull/30175. Your Stackblitz doesn't work, because it's using Angular 18.2. Here's a working Stackblitz: https://stackblitz.com/edit/components-issue-starter-qxkrfxrz?file=package.json

**Comment by rbalet** [comment]
@crisbeto You're right, thx a lot. 

Somehow this is still not working on my own project, even if I have updated it to the latest v19.2 version and have 1x1 the same code as in Stackblitz...

But then it seems that error is laying somewhere else.
