### ISSUE TITLE
[Table] Sort arrows are not rendered properly in tabs

### ISSUE THREAD

**Issue by kevincaradant** [angular/components#7291]
#### Bug, feature request, or proposal:
BUG
Plunker: https://plnkr.co/edit/Idc73Kn0ViLI4Qpsp98g?p=preview

When you set your sort by default as ASC or DESC like that: 

` @ViewChild(MatSort) mdSort: MatSort;`

`ngOnInit() {this.mdSort.start = 'desc';}`

The arrow is just ugly ( 2 times on 3 ). If you click again on the sort icon, it's pretty :)

BTW: Under IE11 it's always ugly. Same issue or not I don't know

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/6093175/30808452-7369aabc-a1fe-11e7-8e65-10db87f062a7.png)

#### What is the expected behavior?
![image](https://user-images.githubusercontent.com/6093175/30808440-67028672-a1fe-11e7-9e54-9924edde56d1.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.4.3
OS: Windows 7 Pro 64 bits
TS: 2.4.1
Material: 2.0.0-beta.11
Browser: Chrome V60

#### Is there anything else we should know?
Nothing #

**Comment by andrewseguin** [comment]
I was able to reproduce the issue and I suspect what is happening here is that you are setting an invalid direction (e.g. `ascending` instead of `asc`)

Plunker to show issue: https://plnkr.co/edit/vf61Yr6tvDtOlKRr9zeN?p=preview

Can you verify that this was the issue?

Adding PR #7378 that will throw an error if the direction is invalid.

**Comment by kevincaradant** [comment]
@andrewseguin , Have you seen my previous message, why this issue is closed ? 

It's not the same problem as mentioned before.

Regards

**Comment by andrewseguin** [comment]
Hey yeah - let's open this back up to figure out what's going on. Sounds like perhaps animations isn't firing off.

Definitely try and get a plunker going so we can dive into this. Thanks

**Comment by kevincaradant** [comment]
This is the plunker :)

https://plnkr.co/edit/Idc73Kn0ViLI4Qpsp98g?p=preview

**Comment by andrewseguin** [comment]
Great thanks for the repro. Looks like the states are being set properly but the animations framework isn't animating the arrow. I'll talk to the core animations guy to see if we can dive into this and see why it's not triggering.

**Comment by kevincaradant** [comment]
Hello, any news about this bug ? :)

**Comment by andrewseguin** [comment]
Coming soon - looks like this is similar to a wider issue with tabs not playing nice with Angular's content projection. In short, components in tabs are initialized without actually being on the DOM, which breaks for some animations (e.g. expansion panel). Sorry for the wait on this

**Comment by kevincaradant** [comment]
@andrewseguin, don't be sorry. I just asking the status about the issue even if I'm sure, there are some others issues (high priority) which need to be fixed ASAP. 
BTW,  thank you for the explanations :)

**Comment by ciesielskico** [comment]
Still an issue on Angular 5.2.2 and Material 5.1.0

**Comment by andrewseguin** [comment]
Keep an eye on https://github.com/angular/material2/pull/8921 for the fix. When it's merged then you can make it so that your tabs load lazily which means Angular animations will work correctly for content in tabs

**Comment by androidovshchik** [comment]
It's a very very very bad bug (@angular/material^5.2.0)
It occured in mat-tabs, so the single solution is to hide these arrows
why simply not to use images? It's simple and it will work
```
.mat-sort-header-arrow {
  display: none !important;
}
```

**Comment by sielver** [comment]
Using 6.0.0 Beta and lazily-loaded tabs "fixes" the issue but it shouldn't be necessary (also, using lazy tabs is not necessarily wanted depending on the app)...

**Comment by VangelisAlSghir** [comment]
I found a workaround for this:

The first time I change to the tab with the table, I call a method which does the following:

table.ngOnDestroy();
dataSource = new DataSource(data); // This is needed because ngOnDestroy disconnects the data source.
table.ngOnInit();

Note that table is the MatTable object and dataSource is bound to the table:
<mat-table [dataSource]="dataSource" matSort>

It's not a good solution and kind of a hack, but it works for me. Maybe this helps

**Comment by androidovshchik** [comment]
@sielver not working unfortunately

**Comment by sielver** [comment]
@androidovshchik I've had it working on my end. Not an ideal solution but no glitch to be seen.

See [the last sample here](url) for an example for wrapping tabs within `<ng-template matTabContent>`.

**Comment by SaadAhmedSiddiqui** [comment]
@sielver  solution is working(lazy loading) nicely, but put the mat-table in a separate new component, put a flag with *ngIf on the component tag, when you changeTab{ mat-tab-group(selectedTabChange) } to current turn on the flag. If you don't want to make a new component and want to use it on same component then @VangelisAlSghir  works fine but inti/destroy is not a good solution

**Comment by hoangnguyen208** [comment]
+1, waiting for a clean solution or fixes

**Comment by maciaszczykm** [comment]
+1 still exists on 5.2.4 when table is wrapped in `*ngIf`.

**Comment by bastienlemaitre** [comment]
@maciaszczykm 
Wrapping the table with ```*ngIf``` is equal to use ```<ng-template matTabContent>```.
I'm agree with @hoangnguyen208, prefer waiting a clean solution.

**Comment by yuriyovych** [comment]
Any news about this bug?

**Comment by satyendrak17** [comment]
I am facing the same issue. Waiting for the clean solution.

**Comment by Biglr** [comment]
Facing the same issue as well...

**Comment by alexferri** [comment]
Facing the same issue as well...

**Comment by lawmbass** [comment]
Just ran across this issue today 😢

**Comment by Barbiero** [comment]
Hey,

While we wait for 6.0 to come out of beta, I've figured a workaround. I force the arrows to be transformed into the expected state on SCSS, so that they don't look ugly when loading the table the first time. Any hover over the arrows will override this workaround, so the default behavior won't be affected:

    ::ng-deep .mat-sort-header-arrow.ng-trigger.ng-trigger-arrowPosition {
        opacity: 0;
    }
    
    ::ng-deep .mat-sort-header-pointer-left.ng-trigger.ng-trigger-leftPointer{
        transform: rotate(-45deg);
    }
    ::ng-deep .mat-sort-header-pointer-right.ng-trigger.ng-trigger-rightPointer{
        transform: rotate(45deg);
    }

**Comment by hoangnguyen208** [comment]
Thanks @Barbiero, it works for now while we are all waiting for a stable fix

**Comment by mikecabana** [comment]
@Barbiero Awesome fix for now!

**Comment by WaltDaniels** [comment]
Thanks @Barbiero, this worked for me as well!

**Comment by LautaroLorenz** [comment]
@Barbiero solution worked for me, very thanks

**Comment by ruskom** [comment]
Thanks @Barbiero

**Comment by ShengTi** [comment]
Thanks @Barbiero this solution works fine

**Comment by edouardsouan** [comment]
To complete @ganeshkantu sayings, the arrow appears for the active sortable column **only** on sort action (click on the column). 

Turning the `opacity ` to 1 seems to fix the default sort display. 
Also I've noticed that the attribute `[@arrowOpacity]` is set with the function `_getArrowViewState()`. 

Does anyone know how this state work ?

**Comment by eyalewin** [comment]
using @Barbiero fix has two issues for me:
1. if using the `opacity:0` than the arrows are hidden
2. when using the `transform`, the arrows are shown well, but the click isn't changing the direction (asc/desc)
is that the issue as well for all of you?

my code looks like this:

```
 <mat-table #table [dataSource]="renderedDataSource" matSort="sort">
        <ng-container *ngFor="let col of columnDefs | columnDefinitionFilter" matColumnDef="{{col.field}}">
            <mat-header-cell *matHeaderCellDef mat-sort-header> {{col.headerName}}</mat-header-cell>
            <mat-cell *matCellDef="let row">
                <span>{{someData}}</span>             
            </mat-cell>
        </ng-container>
```

**Comment by Maxlmore** [comment]
So even with Version 6.0.1, this misbehaviour still occurs :(

**Comment by gabaril** [comment]
Same here. Can't wait to have an update on this matters. This glitch is killing me!

**Comment by gabaril** [comment]
Scratch that, lazy-loading the tab content seems to fix the issue. 
Try putting <ng-template matTabContent></ng-template> around your tab content to fix the rendering issue.

**Comment by Derekjohnson277** [comment]
@gabaril That did it for me!

**Comment by SENSEi-Chris** [comment]
tl:dr - Upgrade to Material 6.3.0.

In case anyone is coming up on this bug now - it appears to have been resolved for Material 6.3.0. At the time I post this a lot of new projects (including mine) were starting on Material 6.2.1, as there was/is a bug in the new Angular 6 `ng add @angular/material` command in combination with Material 6.3.0, meaning one had to fall back on the older version, which still contained the table header bug.

**Comment by stephenautomatik** [comment]
It's still an issue for me after upgrading, but only noticeable when hovering over sort headings or switching back and forth between tabs.

Currently on ng 6.1.2 and material 6.4.3

**Comment by harinikprabhu** [comment]
After three consecutive clicks on the sort arrow, the arrow seems to disappear for me. Is this the expected behavior?

**Comment by fknebels** [comment]
Will this be backported to Angular 5 if fixed?  I just ran into this in 5.2.5 and we've only got corporate approval for Angular 5.

**Comment by eddyzhu1980** [comment]
which material version has the fix? so I can upgrade to it.

**Comment by SebasWebDev** [comment]
I fixed it with default CSS. As the script adds the styling inline, that styling will overwrite the default CSS, so the arrows will show as expected.
`.mat-table {
    .mat-header-cell {
      .mat-sort-header-arrow {
        opacity: 0;
        transform: translateY(0px);
        .mat-sort-header-pointer-left {
          transform: rotate(-45deg);
        }
        .mat-sort-header-pointer-right {
          transform: rotate(45deg);
        }
      }
    }
  }`

**Comment by EasiGregory** [comment]
Presently on angular-material v6.3.0

I have multiple tabs that contain sortable tables, this sort arrow render issue only shows its head on one of them. After the initial click of that column header, the arrow is then rendered as expected until the page is reloaded.

Any update on a fix for this issue?

**Comment by EricParks** [comment]
<img width="927" alt="material-table-t" src="https://user-images.githubusercontent.com/4140315/50405618-aca43c00-0785-11e9-934c-0e1d58def536.png">
Still an issue for me in Material 7.2.0. Can't put a sortable table inside of a mat tab group. The table header arrow changes to a "T" after clicking one of the parent tabs.

**Comment by manishvyas1911** [comment]
The issue was due to mat-table in mat-tab
You just need to lazy load mat-tab.
<ng-template matTabContent>

</ng-template>

**Comment by eddyzhu1980** [comment]
> The issue was due to mat-table in mat-tab
> You just need to lazy load mat-tab.

Thank you very much.  It works perfectly.

**Comment by IrinaPyl** [comment]
I still have this issue https://gyazo.com/d5b184b83fe43eb58196705ac5d9a4c6 with navigation tabs `mat-tab-nav-bar`.
Angular: 7.2.15
Material: 7.2.2
Typescript: 3.2.4
Chrome: 74.0.3729.157 (Official Build) (64-bit)
OS: macOS Mojave 10.14.4

**Comment by vzR** [comment]
same issue present also in the current angular-material documentation https://material.angular.io/components/table/overview#sorting
![image](https://user-images.githubusercontent.com/11074370/61888868-a08f8100-af04-11e9-97fd-5d9bae6d9956.png)

Chrome: Version 75.0.3770.142 (Official Build) (64-bit)
OS: Windows 10 64-bit

**Comment by femt0** [comment]
I still have rendering issues with these arrows : 
<img width="497" alt="Screenshot 2020-01-24 at 13 16 07" src="https://user-images.githubusercontent.com/13162553/73068565-d3aecf00-3eab-11ea-820a-1589701d4a14.png">

Angular: 8.3.20
Material: 8.2.3
Typescript: 3.5.3
Chrome: 79.0.3945.117 (Official Build) (64-bit)
OS: macOS Mojave 10.14.6

**Comment by MoshinaT** [comment]
> Scratch that, lazy-loading the tab content seems to fix the issue.
> Try putting <ng-template matTabContent></ng-template> around your tab content to fix the rendering issue.
> https://material.angular.io/components/tabs/overview#lazy-loading

But it is removing the sorting functionality
